export const types = {
    // Sync
    FILL_TASKS:  'FILL_TASKS',
    CREATE_TASK: 'CREATE_TASK',
    UPDATE_TASK: 'UPDATE_TASK',
    REMOVE_TASK: 'REMOVE_TASK',

    // Async
    FETCH_TASKS_ASYNC: 'FETCH_TASKS_ASYNC',
    CREATE_TASK_ASYNC: 'CREATE_TASK_ASYNC',
    UPDATE_TASK_ASYNC: 'UPDATE_TASK_ASYNC',
    REMOVE_TASK_ASYNC: 'REMOVE_TASK_ASYNC',
};
